version: '3.6'

services:
  logicom-db:
    image: mysql
    container_name: demo
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: demo
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: demo
    restart: always